# Generated by Django 4.1.7 on 2023-02-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "cliente"),
                    (2, "helper"),
                    (3, "atendente"),
                    (4, "gerente"),
                    (5, "admin"),
                ],
                null=True,
            ),
        ),
    ]
